services:
  mteam-downloader:
    image: renjianhuashui/mteam-rss:arm64
    container_name: mteam-downloader
    restart: unless-stopped
    ports:
      - "8080:8080"  # Web界面端口
    volumes:
      - ./config:/app/config
      - ./torrents:/app/torrents
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
